name: Semgrep SAST

on: [push, pull_request]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - name: Run Semgrep Scan
        run: semgrep scan --config=auto .
